#!/usr/bin/env python3
"""Refresh data/universe/us_equities.txt from NASDAQ Trader symbol directories.

Sources:
  - https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt
  - https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt (NYSE common only)

Filters out ETFs, test issues, warrants, units, preferreds, etc.
Yahoo Finance: class shares use dashes (BRK.B → BRK-B).
"""

from __future__ import annotations

import csv
import subprocess
import sys
import urllib.request
from pathlib import Path

NASDAQ_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"
OTHER_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"
ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "data" / "universe" / "us_equities.txt"

_BAD_NAME_FRAGMENTS = (
    "warrant",
    " unit",
    " units",
    " right",
    " rights",
    "preferred",
    "cumulative redeemable",
    "senior note",
    "senior notes",
    "debenture",
    " etn",
    " notes due",
    " note due",
    "trust preferred",
    "depositary shares, each representing",
    "representing 1/1000",
    "representing 1/100",
)

_BAD_SYMBOL_SUFFIXES = (".W", ".WS", ".U", ".R", "-U", "-WS", "-WT", "-UN", "-R")


def to_yahoo_symbol(symbol: str) -> str:
    return symbol.strip().upper().replace(".", "-")


def _bad_name(name: str) -> bool:
    lower = name.lower()
    if any(fragment in lower for fragment in _BAD_NAME_FRAGMENTS):
        return True
    if " fund" in lower and "common stock" not in lower:
        if "common shares" in lower or "fund common" in lower:
            return True
    return False


def _bad_symbol(sym: str) -> bool:
    if not sym or "$" in sym or "+" in sym:
        return True
    return any(suffix in sym for suffix in _BAD_SYMBOL_SUFFIXES)


def fetch_text(url: str) -> str:
    try:
        import ssl

        ctx = ssl.create_default_context()
        with urllib.request.urlopen(url, timeout=60, context=ctx) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except Exception:
        proc = subprocess.run(["curl", "-sS", url], check=True, capture_output=True, text=True)
        return proc.stdout


def nasdaq_common(rows: list[dict[str, str]]) -> set[str]:
    out: set[str] = set()
    for row in rows:
        sym = row.get("Symbol", "").strip()
        if not sym or sym == "Symbol" or sym.startswith("File Creation"):
            continue
        name = row.get("Security Name", "").strip()
        if row.get("ETF") == "Y" or row.get("Test Issue") == "Y":
            continue
        sym_u = sym.upper()
        if _bad_symbol(sym_u) or _bad_name(name):
            continue
        if " " in sym_u:
            continue
        out.add(to_yahoo_symbol(sym))
    return out


def nyse_common(rows: list[dict[str, str]]) -> set[str]:
    out: set[str] = set()
    for row in rows:
        if row.get("Exchange") != "N":
            continue
        if row.get("ETF") == "Y" or row.get("Test Issue") == "Y":
            continue
        sym = row.get("ACT Symbol", "").strip()
        name = row.get("Security Name", "").strip()
        sym_u = sym.upper()
        if _bad_symbol(sym_u) or _bad_name(name):
            continue
        out.add(to_yahoo_symbol(sym))
    return out


def build_us_list() -> list[str]:
    nasdaq_rows = list(csv.DictReader(fetch_text(NASDAQ_URL).splitlines(), delimiter="|"))
    other_rows = list(csv.DictReader(fetch_text(OTHER_URL).splitlines(), delimiter="|"))
    tickers = nasdaq_common(nasdaq_rows) | nyse_common(other_rows)
    return sorted(tickers)


def write_universe(tickers: list[str], path: Path = OUT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# US common equities (NASDAQ + NYSE) — Yahoo Finance symbols\n"
        f"# Sources: {NASDAQ_URL}\n"
        f"#          {OTHER_URL}\n"
        f"# Generated by scripts/refresh_us_equities.py — {len(tickers)} symbols\n"
        "#\n"
    )
    path.write_text(header + "\n".join(tickers) + "\n")


def main() -> int:
    tickers = build_us_list()
    write_universe(tickers)
    print(f"Wrote {len(tickers)} US symbols → {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
