#!/usr/bin/env python3
"""Refresh data/universe/nyse.txt from NASDAQ Trader otherlisted.txt.

Source: https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt

Filters (NYSE common equities only):
  - Exchange == N (NYSE; excludes NYSE American, ARCA, BATS)
  - ETF column != Y
  - Test Issue != Y
  - Symbol excludes $ (preferred) and + (warrants/units)
  - Symbol suffix excludes .W/.WS/.U/.R and -U/-WS/-WT/-UN/-R
  - Name excludes warrant, unit, right, preferred, notes, debentures, etc.
  - Closed-end fund common shares excluded (Fund + Common Shares, not Common Stock)

Yahoo Finance: class shares use dashes (BRK.B → BRK-B).
"""

from __future__ import annotations

import csv
import sys
import urllib.request
from pathlib import Path

SOURCE_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"
ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "data" / "universe" / "nyse.txt"

_BAD_NAME_FRAGMENTS = (
    "warrant",
    " unit",
    " units",
    " right",
    " rights",
    "preferred",
    "cumulative redeemable",
    "senior note",
    "senior notes",
    "debenture",
    " etn",
    " notes due",
    " note due",
    "trust preferred",
    "depositary shares, each representing",
    "representing 1/1000",
    "representing 1/100",
)

_BAD_SYMBOL_SUFFIXES = (".W", ".WS", ".U", ".R", "-U", "-WS", "-WT", "-UN", "-R")


def to_yahoo_symbol(nasdaq_symbol: str) -> str:
    return nasdaq_symbol.strip().upper().replace(".", "-")


def is_nyse_common_stock(symbol: str, name: str, row: dict[str, str]) -> bool:
    if row.get("Exchange") != "N":
        return False
    if row.get("ETF") == "Y" or row.get("Test Issue") == "Y":
        return False

    sym = symbol.strip().upper()
    if not sym or "$" in sym or "+" in sym:
        return False
    if any(suffix in sym for suffix in _BAD_SYMBOL_SUFFIXES):
        return False

    lower = name.lower()
    if any(fragment in lower for fragment in _BAD_NAME_FRAGMENTS):
        return False
    if " fund" in lower and "common stock" not in lower:
        if "common shares" in lower or "fund common" in lower:
            return False
    return True


def fetch_rows() -> list[dict[str, str]]:
    import ssl
    import subprocess

    try:
        ctx = ssl.create_default_context()
        with urllib.request.urlopen(SOURCE_URL, timeout=60, context=ctx) as resp:
            text = resp.read().decode("utf-8", errors="replace")
    except Exception:
        proc = subprocess.run(
            ["curl", "-sS", SOURCE_URL],
            check=True,
            capture_output=True,
            text=True,
        )
        text = proc.stdout
    return list(csv.DictReader(text.splitlines(), delimiter="|"))


def build_nyse_list(rows: list[dict[str, str]]) -> list[str]:
    tickers: set[str] = set()
    for row in rows:
        sym = row.get("ACT Symbol", "").strip()
        name = row.get("Security Name", "").strip()
        if sym and is_nyse_common_stock(sym, name, row):
            tickers.add(to_yahoo_symbol(sym))
    return sorted(tickers)


def write_universe(tickers: list[str], path: Path = OUT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# NYSE common equities — Yahoo Finance symbols\n"
        f"# Source: {SOURCE_URL}\n"
        f"# Generated by scripts/refresh_nyse_universe.py — {len(tickers)} symbols\n"
        "#\n"
    )
    path.write_text(header + "\n".join(tickers) + "\n")


def main() -> int:
    rows = fetch_rows()
    tickers = build_nyse_list(rows)
    write_universe(tickers)
    print(f"Wrote {len(tickers)} NYSE symbols → {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
